[package]
name = "nesemu"
version = "0.1.0"
authors = ["Joshua Ford <joshua.ford@protonmail.com>"]
edition = "2018"

[lib]
name = "cpu"
path = "src/lib/cpu/lib.rs"

[dependencies]
lazy_static = "1.4.0"
